Repository CoffeeNaeriRei/ScreenTime_Barebones, pull requests merged in 2023-08, with the labels that each got.

#1 [Test]: Fork Test
  ScreenTime_Barebones/ContentView.swift
Labels: good first issue

#9 [Feat]: ScheduleView 레이아웃 작성
  ScreenTime_Barebones.xcodeproj/project.pbxproj
  ScreenTime_Barebones/App/ContentView.swift
  ScreenTime_Barebones/Presentation/ContentView.swift
  ScreenTime_Barebones/Presentation/ViewModels/Components/MainTabVM.swift
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
  ScreenTime_Barebones/Presentation/Views/Components/MainTabView.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
  ScreenTime_Barebones/Utils/DeviceActivtyManager.swift
Labels: Feat

#11 [Chore]: 뷰코드 정리 및 주석 작성 Close #8
  .swiftlint.yml
  ScreenTime_Barebones.xcodeproj/xcshareddata/xcschemes/DeviceActivityMonitor.xcscheme
  ScreenTime_Barebones.xcodeproj/xcshareddata/xcschemes/ScreenTime_Barebones.xcscheme
  ScreenTime_Barebones.xcodeproj/xcshareddata/xcschemes/ShieldAction.xcscheme
  ScreenTime_Barebones.xcodeproj/xcshareddata/xcschemes/ShieldConfiguration.xcscheme
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
  ScreenTime_Barebones/Utils/DeviceActivtyManager.swift
Labels: Chore

#14 [Feat] 스케줄 설정 이후 실제 제한 적용되도록 코드 작성 #8
  DeviceActivityMonitor/DeviceActivityMonitor.entitlements
  DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  ScreenTimeReport/ScreenTimeReport.swift
  ScreenTimeReport/TotalActivityReport.swift
  ScreenTimeReport/TotalActivityView.swift
  ScreenTime_Barebones.xcodeproj/project.pbxproj
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
  ScreenTime_Barebones/Utils/DeviceActivtyManager.swift
Labels: Feat

#16 [Refactor] DeviceActivityManager 수정
  DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
  ScreenTime_Barebones/Utils/DeviceActivtyManager.swift
Labels: Fix, Feat, Refactor

#18 [Fix] ScheduleVM.swift 및 스케줄 모니터링 관련 코드수정
  DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
  ScreenTime_Barebones/Utils/DeviceActivtyManager.swift
Labels: Fix, Feat

#21 [Feat]: PermissionView 작성 및 UI 동작 개선 Close #13
  .gitignore
  DeviceActivityMonitor/Info.plist
  ScreenTime-Barebones-Info.plist
  ScreenTime_Barebones.xcodeproj/project.pbxproj
  ScreenTime_Barebones/App/ScreenTime_BarebonesApp.swift
  ScreenTime_Barebones/App/XCConfig/shared.xcconfig
  ScreenTime_Barebones/Assets.xcassets/AppSymbol.imageset/AppIcon.png
  ScreenTime_Barebones/Assets.xcassets/AppSymbol.imageset/Contents.json
  ScreenTime_Barebones/Extension/Bundle+Extension.swift
  ScreenTime_Barebones/Extension/Color+Extension.swift
  ScreenTime_Barebones/Presentation/ViewModels/PermissionVM.swift
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
  ScreenTime_Barebones/Presentation/Views/PermissionView/PermissionView.swift
  ShieldConfiguration/AppSymbol.png
  ShieldConfiguration/ShieldConfigurationExtension.swift
Labels: Feat, Design

#22 [Feat] MonitoringView 작성 #10
  ScreenTimeReport/ScreenTimeActivityReport.swift
  ScreenTimeReport/ScreenTimeReport.swift
  ScreenTimeReport/TotalActivityReport.swift
  ScreenTimeReport/TotalActivityView.swift
  ScreenTime_Barebones.xcodeproj/project.pbxproj
  ScreenTime_Barebones/Presentation/Views/MonitoringView/MonitoringView.swift
Labels: Feat

#27 [Setting] 개발자 팀 추가 후 Provisioning profile 및 Certificate 공유할 수 있도록 설정
  DeviceActivityMonitor/DeviceActivityMonitor.entitlements
  ScreenTime_Barebones.xcodeproj/project.pbxproj
  ScreenTime_Barebones/App/XCConfig/shared.xcconfig
  ScreenTime_Barebones/ScreenTime_Barebones.entitlements
Labels: Setting

#29 [Design] MonitoringView 디자인 수정 Close #28
  DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  ScreenTimeReport/ScreenTimeActivityReport.swift
  ScreenTimeReport/TotalActivityReport.swift
  ScreenTimeReport/TotalActivityView.swift
  ScreenTime_Barebones.xcodeproj/project.pbxproj
  ScreenTime_Barebones/Extension/Bundle+Extension.swift
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
Labels: Design
