Repository CoffeeNaeriRei/ScreenTime_Barebones, pull requests merged in 2023-09, with the labels that each got.

#30 [Feat] MonitoringView 개선 작업
  ScreenTimeReport/TotalActivityReport.swift
  ScreenTimeReport/TotalActivityView.swift
Labels: Feat

#31 [Feat] MonitoringView 개선 작업 #25
  ScreenTimeReport/TotalActivityView.swift
  ScreenTime_Barebones/Presentation/ViewModels/ScheduleVM.swift
  ScreenTime_Barebones/Presentation/Views/MonitoringView/MonitoringView.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
Labels: Fix

#34 [Fix] ScheduleVM 클래스를 @EnvironmentObject로 사용하도록 수정 #33
  DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  ScreenTime_Barebones/App/ScreenTime_BarebonesApp.swift
  ScreenTime_Barebones/Presentation/Views/MonitoringView/MonitoringView.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
Labels: Fix

#36 Update README.md
  README.md
Labels: Docs

#38 [Fix] 앱 잠금 미적용 / 다크모드 수정
  DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  ScreenTimeReport/TotalActivityView.swift
  ScreenTime_Barebones/Presentation/Views/ScheduleView/ScheduleView.swift
Labels: Fix

#37 Update README.md
  README.md
Labels: Docs

#40 Update README.md
  README.md
Labels: Docs
